name: "public"

services:

####################
# Reverse Proxy
####################

  caddy:
    container_name: caddy
    build:
      context: ./dockerfiles
      dockerfile: caddy.dockerfile #Custom build which uses duckdns. Control image version in this file

    networks:
      - default

    ports:
      - ${PORT_CADDY_HTTP}:80
      - ${PORT_CADDY_HTTPS}:443
      - ${PORT_CADDY_HTTPS}:443/udpCADDY_ACME_CA
      - ${PORT_CADDY_ADMIN}:2019

    environment:
      LOG_FILE: ${LOGDIR}/caddy/access.log
      DOMAIN: ${DOMAIN}
      EMAIL: ${EMAIL_ADMIN}
      DUCKDNS_API_TOKEN: ${DUCKDNS_TOKEN}
      
      BOUNCER_CADDY_TOKEN: ${BOUNCER_CADDY_TOKEN}

    volumes:
      - ${CADDY_CONFIG_DIR}/caddy/Caddyfile:/etc/caddy/Caddyfile:ro

    healthcheck:
      test: ["CMD", "caddy", "version"]
    restart: unless-stopped


####################
# Dynamic DNS
####################  
  
  duckdns:
    container_name: duckdns
    image: ghcr.io/linuxserver/duckdns

    networks:
      - default

    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      SUBDOMAINS: ${DUCKDNS_SUBDOMAINLIST}
      TOKEN: ${DUCKDNS_TOKEN}

    labels:
      - homepage.group=Wild West
      - homepage.name=DuckDNS
      - homepage.icon=duckdns
      - homepage.description=Dynamic DNS for external access
    volumes:
      - ${CONFIGDIR}/duckdns:/config #optional

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 32M
    restart: unless-stopped


networks:
  default:
    name: homelab-network
