---
allowedHosts:
  - localhost
  - 127.0.0.1
  - homepage
  - homepage.gsofianos.duckdns.org
title: Sofianos Server Dashboard
header: true
headerStyle: boxedWidgets
footer: false
cardBlur: xs
fullWidth: false
useEqualHeights: true
theme: dark
color: slate
disableCollapse: true
bookmarksStyle: icons
showStats: true
disableIndexing: true

layout:
  Main Container:
    header: false
    style: row
    columns: 4

    Media:
      header: true
      Media-Main:
        header: false
      Immich-More:
        header: false
        style: row
        columns: 2

    AI Tools:
      header: true

    Apps:
      header: true

#    Host Nodes:
#      header: true