---
allowedHosts:
  - localhost
  - 127.0.0.1
  - homepage
  - homepage.gsofianos.duckdns.org

title: Sofianos Server Dashboard
logo: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/shoko-server.png
header: true
headerStyle: boxedWidgets
footer: false
cardBlur: xs
statusStyle: "dot"

layout:
  Host Nodes:
    style: row
    columns: 2
  Media:
    style: row
    columns: 2
  AI Tools:
    style: row
    columns: 2
  Apps:
    style: clean
    columns: 4
    iconsOnly: true

