name: laptop1-homelab

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    environment:
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
      - EMAIL=${CADDY_EMAIL}

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    volumes:
      - homepage-config:/app/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    volumes:
      - /opt/jellyfin:/config
      - /mnt/seagate_storage/jellyfin/media:/media:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PUBLISHED_URL}

  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
    container_name: immich-server
    restart: unless-stopped
    volumes:
      - /opt/immich:/usr/src/app/config
      - /mnt/seagate_storage/immich:/usr/src/app/upload
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION}
    container_name: immich-machine-learning
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

  immich-redis:
    image: redis:alpine
    container_name: immich-redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning

  immich-postgres:
    image: postgres:16-alpine
    container_name: immich-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=immich
      - POSTGRES_DB=immich
    volumes:
      - immich-db:/var/lib/postgresql/data

  pricebuddy:
    image: jez500/pricebuddy:latest
    container_name: pricebuddy
    restart: unless-stopped
    volumes:
      - pricebuddy-data:/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

# ====================== VOLUMES ======================
volumes:
  caddy-data:
  caddy-config:
  homepage-config:
  immich-db:
  pricebuddy-data:
