name: laptop1-homelab

include:
  - path: ../services/pricebuddy/docker-compose.yml
  - path: ../services/dashboard/docker-compose.yml
  - path: ../services/immich/docker-compose.yml
  - path: ../services/media-streaming/docker-compose.yml
  - path: ../services/public/docker-compose.yml

networks:
  default:
    name: homelab-network
    driver: bridge

volumes:
  jellyfin-config:
  pricebuddy_db: