name: "jellyfin"

services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    user: ${PUID}:${PGID}
    restart: unless-stopped
    
    ports:
      - ${PORT_HTPC_HTTP}:8096
      - ${PORT_HTPC_HTTPS}:8920

    environment:
      TZ: ${TZ}
      JELLYFIN_PublishedServerUrl: ${SERVER_URL}:${PORT_HTPC_HTTP} #optional. The Server URL to publish in udp Auto Discovery response.

    volumes:
      - /opt/jellyfin/config:/config
      - /opt/jellyfin/cache:/cache
      - ${MEDIADIR}:/media:ro
      