name: "homepage"

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage

    ports:
      - 127.0.0.1:${PORT_DASH_HTTP}:3000

    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      LOG_LEVEL: 'debug'
      HOMEPAGE_ALLOWED_HOSTS: localhost,127.0.0.1,${SERVER_URL},${HOST_NAME}.${HOST_DOMAIN},${HOST_DOMAIN}

    volumes:
      - ${HOMEPAGE_CONFIG_DIR}/homepage:/app/config
      - /mnt/seagate_storage:/mnt/seagate_storage:ro
      - /:/host:ro
      - /sys:/sys:ro
      - ./icons:/app/public/icons
    
    healthcheck:
      test: wget --spider http://${SERVER_URL}:${PORT_SOCKY_PROXY}/version || exit 1
      interval: "180s"
      timeout: "5s"
      retries: 3
      start_period: "30s"

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    restart: unless-stopped
    