name: homelab-ai

include:
  - path: ../services/ai/ollama/docker-compose.yml
  - path: ../services/ai/open-webui/docker-compose.yml
  - path: ../services/dockerproxy/docker-compose.yml
  - path: ../services/glances/docker-compose.yml

networks:
  default:
    name: homelab-ai-network
    driver: bridge
