name: homelab-media

include:
  - path: ../services/pricebuddy/docker-compose.yml
  - path: ../services/homepage/docker-compose.yml
  - path: ../services/immich/docker-compose.yml
  - path: ../services/jellyfin/docker-compose.yml
  - path: ../services/public/docker-compose.yml
  - path: ../services/dockerproxy/docker-compose.yml

networks:
  homelab-media-network:
    name: homelab-media-network
    driver: bridge

volumes:
  jellyfin-config:
  pricebuddy_db: